In [3]:
import numpy as np

# Creating arrays from Python Lists

Example of a Python list that contains multiple data types

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [7]:
# all data types in array need to be the same
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [8]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

Unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [9]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating arrays from scratch 

For large arrays, it's more efficient to create arrays from scratch using routine built into Numpy. Here are serveral examples:

In [10]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# create an array filled with a linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.58745089, 0.08406031, 0.98462844],
       [0.07578418, 0.05530651, 0.78641544],
       [0.93918724, 0.70831419, 0.26689012]])

In [17]:
# create a 3x3 array of uniformly distributed random values with mean 0 and sd 1
np.random.normal(0, 1, (3, 3))

array([[-0.71603961,  0.53079222,  0.88905856],
       [-0.20184254, -2.09496292, -0.32654479],
       [ 1.21014619,  0.2614705 ,  0.32027854]])

In [18]:
# create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0, 10, (3, 3))

array([[3, 0, 8],
       [5, 4, 8],
       [6, 5, 5]])

In [20]:
# create a 3x3 identity matrix
np.eye(3)
# the identity matrix, or sometimes ambiguously called a unit matrix, of size n is the n × n square matrix with ones on 
# the main diagonal and zeros elsewhere. The effect of multiplying a given matrix by an identity matrix is to leave the 
# given matrix unchanged.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy standard data types

It can be specified in dtype with string or Numpy object

In [22]:
np.zeros(10, dtype = 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [23]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

#### Other common date types:<br>
- bool_ <br>
- int_ (same as int32 or int64)<br>
- int8<br>
- int16<br>
- int32<br>
- int64<br>
- float_ (same as float64)<br>
- float16<br>
- float32<br>
- float64 <br>